### ISSUE TITLE
PSTAT example incomplete

### ISSUE THREAD

**Issue by ashwinvis** [KTH-Nek5000/KTH_Examples#3]
The runtime parameters for PSTAT module are unused in the [.par file](https://github.com/KTH-Nek5000/KTH_Examples/blob/master/phill_PSTAT/phill.par).

https://github.com/KTH-Nek5000/KTH_Examples/blob/8c1f04bbfd16af04c4494f1ac9dd0a1e1426f9a5/phill_PSTAT/pstat.f#L73-L84

**Comment by adampep** [comment]
Corrected
