### ISSUE TITLE
DNS_ext_cyl

### ISSUE THREAD

**Issue by AdwardAllan** [KTH-Nek5000/KTH_Examples#4]
Dear nek5000-developers:
      Thanks for attentions. I want to run this example for comNS , could you help me to modify file/parameter.
Best wish to you,
Sincerely,
lixinjun

**Comment by danielemassaro** [comment]
Dear Lixinjun,

In Nek5000 there is a Low Mach variable density formulation,
but there is no fully compressible NS.

Sincerely,
Daniele
